# -*- coding: utf-8 -*-
"""Quarterly Revenue Regression Analysis

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1suir0nYyiadFaqL7RAgdjvscAiXtpAo_
"""

import numpy as np
from sklearn.linear_model import LinearRegression

# Function to get input quarterly revenue data from the user
def get_input_revenue():
    revenue = []
    quarters_order = {'1st': 1, '2nd': 2, '3rd': 3, '4th': 4}

    while True:
        quarter_input = input("Enter the quarter (1st/2nd/3rd/4th) or 'done' to finish: ").lower()
        if quarter_input == 'done':
            break
        year_input = input("Enter the year: ")
        while True:
            try:
                rev = float(input(f"Enter revenue for {quarter_input} quarter of {year_input}: "))
                revenue.append((quarters_order[quarter_input], int(year_input), rev))
                break
            except ValueError:
                print("Please enter a valid revenue amount.")

    return revenue

# Function to predict the revenue for the next quarter
def predict_next_revenue(revenue):
    X = np.array([(q, y) for q, y, _ in revenue])  # quarters and years
    y = np.array([r for _, _, r in revenue])       # revenue

    # Fit linear regression model
    model = LinearRegression()
    model.fit(X, y)

    # Predict revenue for the next quarter in chronological order
    latest_quarter, latest_year, _ = max(revenue)
    next_quarter = latest_quarter + 1 if latest_quarter < 4 else 1
    next_year = latest_year if next_quarter != 1 else latest_year + 1

    next_revenue = model.predict([[next_quarter, next_year]])
    return next_revenue[0]

# Main function
def main():
    print("Enter the historical quarterly revenue data. Enter 'done' when finished.")
    revenue_data = get_input_revenue()

    if len(revenue_data) < 2:
        print("Please enter revenue data for at least two quarters to predict the next quarter's revenue.")
    else:
        next_revenue = predict_next_revenue(revenue_data)
        print(f"The predicted revenue for the next quarter is: {next_revenue}")

if __name__ == "__main__":
    main()